common_data:
  image: "ubuntu"
  volumes:
      - ./html:/usr/share/nginx/html

nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes_from:
      - "common_data"
    volumes:
      - ./etc/ngConf.d:/etc/nginx/conf.d

php:
    build: ./Dockerfiles/php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes_from:
      - "common_data"
    volumes:
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

redis:
    image: redis
    ports:
      - "6379:6379"