version: "3"
services:
  nginx:
      image: nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./etc/ngConf.d:/etc/nginx/conf.d
        - ./etc/nginx/php.conf:/etc/nginx/php.conf
        - ${DEFAUL_PROJECT}:/default_project/
        - ${PROJECTS}:/projects/
        - ./volumes/logs/nginx:/ronie/logs/nginx
        - ${SSL_CRT}:/ronie/ssl/server.crt
        - ${SSL_KEY}:/ronie/ssl/server.key

  php:
      build: ./Dockerfiles/php
      volumes:
        - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ${DEFAUL_PROJECT}:/default_project/
        - ${PROJECTS}:/projects/
      environment:
        APP_ENV: "development"

  mysql:
      image: mysql:5.7.22
      volumes:
        - ./mysqlData:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456

  redis:
      image: redis

networks:
  default:
    external:
      name: ${NETWORK_NAME}
