common_data:
  image: "ubuntu"
  volumes:
      - ./project:/project/
      - ~/dadaabc/code/:/projects/
      - ./dockerDisk:/ronieDisk
      - ./dockerDisk/var/www/logs:/var/www/logs

nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - "common_data"
    volumes:
      - ./etc/ngConf.d:/etc/nginx/conf.d
    links:
      - "php"

php:
    build: ./Dockerfiles/php
    volumes_from:
      - "common_data"
    volumes:
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      DADA_ENV: "dev"
      DADA_DEV: "dev"
    extra_hosts:
      - "dev-service.dadaabc.us:192.168.146.44"
